%YAML 1.2
---
logging: !include logging.yaml

url:
  grafana: !envopt GRAFANA_URL

database:
  default:
    url: !env INFLUXDB_URL
    username: !envopt INFLUXDB_USERNAME
    password: !envopt INFLUXDB_PASSWORD
    database: !env INFLUXDB_USER_DATABASE
    buffer_interval: 1
  shared:
    url: !env INFLUXDB_URL
    username: !envopt INFLUXDB_USERNAME
    password: !envopt INFLUXDB_PASSWORD
    database: !env INFLUXDB_SHARED_DATABASE
    buffer_interval: 1

hardware: !include '{config_path}/hardware.yaml'

remap:
  event: shared
  linkam: shared
  mfc_*: shared
  server: shared

procedure:
  pulse:
    # Default flow rate
    flow: '200 sccm'

    # Default gas balance
    normal:
      air: balance

pushover:
  title: !format '{app_name} {system_hostname}'
  api_token: !envopt PUSHOVER_API_KEY
  user_key: !envopt PUSHOVER_USER_KEY
  user_device: !envopt PUSHOVER_USER_DEVICE

server:
  host: !envopt EXPERIMENTSERVER_HOST 0.0.0.0
  port: !envopt EXPERIMENTSERVER_PORT 5000

...
