%YAML 1.2
---
logging: !include logging.yaml

url:
  grafana: !envopt GRAFANA_URL

database:
  default:
    url: !env INFLUXDB_V2_URL
    org: !env INFLUXDB_V2_ORG
    token: !env INFLUXDB_V2_TOKEN
    bucket: !env INFLUXDB_V2_BUCKET

hardware: !include '{config_path}/hardware.yaml;C:/GasSensing/config/hardware.yaml'

remap: []

procedure:
  # Default configuration for procedures
  pulse:
    experiment: Unknown
    sample: Unknown

pushover:
  title: !format '{app_name} {system_hostname}'
  api_token: !envopt PUSHOVER_API_KEY
  user_key: !envopt PUSHOVER_USER_KEY
  user_device: !envopt PUSHOVER_USER_DEVICE

server:
  host: !envopt EXPERIMENTSERVER_HOST 0.0.0.0
  port: !envopt EXPERIMENTSERVER_PORT 5000

...
