%YAML 1.2
---
logging: !include logging.yaml

database:
  default:
    host: research.etoast.net
    port: 443
    ssl: True
    path: /influxdb
    username: !env INFLUXDB_SHARED_USERNAME
    password: !env INFLUXDB_SHARED_PASSWORD
    database: !env INFLUXDB_SHARED_DATABASE
  private:
    host: research.etoast.net
    port: 443
    ssl: True
    path: /influxdb
    username: !env INFLUXDB_USER_USERNAME
    password: !env INFLUXDB_USER_PASSWORD
    database: !env INFLUXDB_USER_DATABASE

hardware:
  - !include hardware_mfc.yaml
  - !include hardware_psu.yaml

server: !include server.yaml

...
