%YAML 1.2
---
logging: !include logging.yaml

url:
  grafana: !env GRAFANA_URL

database:
  default:
    url: !envreq INFLUXDB_V2_URL
    org: !envreq INFLUXDB_V2_ORG
    token: !envreq INFLUXDB_V2_TOKEN
    bucket: !envreq INFLUXDB_V2_BUCKET

hardware: !include '{config_path}/hardware.yaml;C:/GasSensing/config/hardware.yaml'

procedure_metadata:
  # Default configuration for procedures
  led_current: ''
  led_optical_power: ''
  led_wavelength: ''
  experiment: '_Unlabelled'
  sample: '_Unlabelled'

pushover:
  title: !format '{app_name} {system_hostname}'
  api_token: !env PUSHOVER_API_KEY
  user_key: !env PUSHOVER_USER_KEY
  user_device: !env PUSHOVER_USER_DEVICE

server:
  host: !env EXPERIMENTSERVER_HOST 0.0.0.0
  port: !env EXPERIMENTSERVER_PORT 5000

...
