%YAML 1.2
---
logging: !include logging.yaml

url:
  grafana: !envopt GRAFANA_URL

database:
  default:
    url: !envopt INFLUXDB_URL http://localhost:8086/
    username: !envopt INFLUXDB_USERNAME
    password: !envopt INFLUXDB_PASSWORD
    database: !envopt INFLUXDB_USER_DATABASE experiment
    buffer_interval: 1
  shared:
    url: !envopt INFLUXDB_URL http://localhost:8086/
    username: !envopt INFLUXDB_USERNAME
    password: !envopt INFLUXDB_PASSWORD
    database: !envopt INFLUXDB_SHARED_DATABASE experiment
    buffer_interval: 1
  log:
    url: !envopt INFLUXDB_URL http://localhost:8086/
    username: !envopt INFLUXDB_USERNAME
    password: !envopt INFLUXDB_PASSWORD
    database: experiment_log
    buffer_interval: 1

hardware: !include '{config_path}/hardware.yaml;C:/GasSensing/config/hardware.yaml'

remap:
  # Remapping of measurements to databases based upon source name
  event: log
  server: log
  linkam: shared
  mfc_*: shared
  valve_*: shared
  ledsupply: shared
  powersupply: shared

procedure:
  # Default configuration for procedures
  pulse:
    balance: air
    flow: 200 sccm

pushover:
  title: !format '{app_name} {system_hostname}'
  api_token: !envopt PUSHOVER_API_KEY
  user_key: !envopt PUSHOVER_USER_KEY
  user_device: !envopt PUSHOVER_USER_DEVICE

server:
  host: !envopt EXPERIMENTSERVER_HOST 0.0.0.0
  port: !envopt EXPERIMENTSERVER_PORT 5000

...
