%YAML 1.2
---
logging: !include logging.yaml

url:
  grafana: !envopt GRAFANA_URL

database:
  default:
    # host: research.etoast.net
    # port: 443
    # ssl: True
    # path: /influxdb
    host: localhost
    username: !env INFLUXDB_SHARED_USERNAME
    password: !env INFLUXDB_SHARED_PASSWORD
    database: !env INFLUXDB_SHARED_DATABASE
  private:
    # host: research.etoast.net
    # port: 443
    # ssl: True
    # path: /influxdb
    host: localhost
    username: !env INFLUXDB_USER_USERNAME
    password: !env INFLUXDB_USER_PASSWORD
    database: !env INFLUXDB_USER_DATABASE

hardware:
  - !include hardware_lcr.yaml
  - !include hardware_linkam.yaml
  - !include hardware_mfc.yaml
  - !include hardware_multimeter.yaml
  - !include hardware_picoammeter.yaml
  - !include hardware_psu.yaml

remap:
  multimeter: private
  powersupply: private

server: !include server.yaml

...
