%YAML 1.2
---
version: 1
disable_existing_loggers: False
formatters:
  console_format:
    format: "%(asctime)s [%(levelname).1s] %(threadName)s %(name)s: %(message)s"
    datefmt: "%y%m%d %H:%M:%S"
  file_format:
    format: "%(asctime)s [%(levelname)s] %(threadName)s@%(filename)s:%(lineno)d %(name)s: %(message)s"
    datefmt: "%Y/%m/%d %H:%M:%S"
handlers:
  stdout_handler:
    class: experimentserver.util.console.ColoramaStreamHandler
    formatter: console_format
    level: INFO
    stream: ext://sys.stdout
  debug_file_handler:
    class: logging.handlers.TimedRotatingFileHandler
    # filename: !format "{path_root}/log/debug.log"
    filename: !format "C:\\Experiment\\Log\\debug.log"
    when: "D"
    formatter: file_format
    level: DEBUG
    encoding: "utf-8"
    backupCount: 3
  instance_file_handler:
    class: logging.FileHandler
    formatter: file_format
    level: INFO
    filename: !format "{path_root}/log/run_{date}_{time}.log"
    encoding: "utf-8"
  database_event_handler:
    class: experimentserver.util.logging.event.DatabaseEventHandler
  pushover_notify_handler:
    class: experimentserver.util.logging.notify.PushoverNotificationHandler
    title: !format '{module_root}'
    api_token: !envopt PUSHOVER_API_KEY
    user_key: !envopt PUSHOVER_USER_KEY
    user_device: !envopt PUSHOVER_USER_DEVICE
root:
  level: DEBUG
  # pushover_notify_handler
  handlers: [stdout_handler, debug_file_handler, instance_file_handler, database_event_handler]
...
