%YAML 1.2
---
version: 1
disable_existing_loggers: False

formatters:
  console_format:
    format: "%(asctime)s [%(levelname).1s] %(threadName)s@%(filename)s %(name)s: %(message)s"
    datefmt: "%y%m%d %H:%M:%S"
  file_format:
    format: "%(asctime)s.%(msecs)03d [%(levelname)s] %(threadName)s@%(filename)s:%(lineno)d %(name)s: %(message)s"
    datefmt: "%Y/%m/%d %H:%M:%S"

handlers:
  stdout_handler:
    class: experimentlib.logging.handlers.console.ColoramaStreamHandler
    formatter: console_format
    level: DEBUG
    stream: ext://sys.stdout

  debug_file_handler:
    class: logging.handlers.RotatingFileHandler
    filename: !format "{root_path}/log/debug.log"
    formatter: file_format
    level: NOTSET
    encoding: "utf-8"
    maxBytes: 134217728
    backupCount: 5

  instance_file_handler:
    class: logging.FileHandler
    formatter: file_format
    level: INFO
    filename: !format "{root_path}/log/run_{datetime}.log"
    encoding: "utf-8"

loggers:
  root:
    level: NOTSET
    handlers: [stdout_handler, debug_file_handler, instance_file_handler]

  # Silence some built-in loggers
  urllib3:
    level: INFO
  urllib3.connectionpool:
    level: INFO
  pyvisa:
    level: INFO
  transitions.core:
    level: INFO
  pymodbus:
    level: INFO
