%YAML 1.2
---
version: 1
disable_existing_loggers: False
formatters:
  console_format:
    format: "%(asctime)s [%(levelname).1s] %(threadName)s@%(filename)s %(name)s: %(message)s"
    datefmt: "%y%m%d %H:%M:%S"
  file_format:
    format: "%(asctime)s [%(levelname)s] %(threadName)s@%(filename)s:%(lineno)d %(name)s: %(message)s"
    datefmt: "%Y/%m/%d %H:%M:%S"
handlers:
  stdout_handler:
    class: experimentserver.util.console.ColoramaStreamHandler
    formatter: console_format
    level: INFO
    stream: ext://sys.stdout
  debug_file_handler:
    class: logging.handlers.TimedRotatingFileHandler
    filename: !format "{temp_path}/experimentserver.log"
    when: "D"
    formatter: file_format
    level: DEBUG
    encoding: "utf-8"
    backupCount: 3
  instance_file_handler:
    class: logging.FileHandler
    formatter: file_format
    level: INFO
    filename: !format "{root_path}/log/run_{date}_{time}.log"
    encoding: "utf-8"
  database_event_handler:
    class: experimentserver.util.logging.event.DatabaseEventHandler
root:
  level: DEBUG
  handlers: [stdout_handler, debug_file_handler, instance_file_handler, database_event_handler]
...
