%YAML 1.2
---
logging:
  version: 1
  disable_existing_loggers: False
  formatters:
    console_format:
      format: "%(asctime)s [%(levelname).1s] %(threadName)s@%(filename)s %(name)s: %(message)s"
      datefmt: "%y%m%d %H:%M:%S"
    file_format:
      format: "%(asctime)s [%(levelname)s] %(threadName)s@%(filename)s:%(lineno)d %(name)s: %(message)s"
      datefmt: "%Y/%m/%d %H:%M:%S"
  handlers:
    stdout_handler:
      class: experimentserver.util.console.ColoramaStreamHandler
      formatter: console_format
      level: INFO
      stream: ext://sys.stdout
    debug_file_handler:
      class: logging.handlers.TimedRotatingFileHandler
      filename: !format "{env_home}/experimentserver.log"
      when: "D"
      formatter: file_format
      level: DEBUG
      encoding: "utf-8"
      backupCount: 3
    database_event_handler:
      class: experimentserver.util.logging.event.DatabaseEventHandler
  root:
    level: DEBUG
    handlers: [stdout_handler, debug_file_handler, database_event_handler]

database:
  default:
    url: 'http://peak-fifteen.rem.etoast.net:8086'
    database: 'experiment'
    buffer_interval: 1

hardware:
  - class: custom.AccelMonitor
    identifier: accelemonitor
    port: 'COM8'
  - class: keithley.MultimeterDAQ6510
    identifier: multimeter
    visa_address: 'USB0::0x05E6::0x6510::04444866::INSTR'

server:
  host: 0.0.0.0
  port: 5000

...
